LibraryProject/urls.py
from django.contrib import admin
from django.urls import path, include
from library_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library_app.urls')),
    path('contact/', views.ContactView.as_view(), name='contact-form'),
    path('success/', views.success_view, name='thanks'),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),



]

blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path('', views.PostHomeView.as_view(), name='blog-home'),
    path('<int:pk>', views.PostDetailView.as_view(), name='blog-detail'),
    path('<int:pk>/update', views.PostUpdateView.as_view(), name='blog-update'),
]

library_app/urls.py
from django.urls import path
from . import views

app_name = 'library_app'

urlpatterns = [
    path('', views.HomeView.as_view(),              name='index'),

    path('catalog/', views.BookListView.as_view(),  name='book-list'),

    path('catalog/<int:pk>', views.BookDetailView.as_view(),
                                                    name='book-detail'),

    path('authors/', views.AuthorListView.as_view(), name='author-list'),

    path('authors/<int:pk>', views.AuthorDetailView.as_view(),
                                                    name='author-detail'),
    path('catalog/addbook', views.AddBookView.as_view(),
                                                    name='add-book'),
    path('authors/addauthor', views.AddAuthorView.as_view(),
                                                    name='add-author'),
    path('authors/<int:pk>/editauthor', views.UpdateAuthorView.as_view(),
                                                    name='edit-author'),
    # path()



]

library_app/models.py
from django.db import models
from django.urls import reverse
import uuid #universally unique identifiers for book instances


class Genre(models.Model):
    """Model representing a book genre"""
    name = models.CharField(max_length=200,
                help_text='Enter a book genre (e.g. Science Fiction)',
                default=None)

    def __str__(self):
        """String representation of the Model object"""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)"""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000,
                help_text='Enter a brief description of the book',
                null=True, blank=True)
    isbn = models.CharField('ISBN', max_length=13,
    help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
    null=True, blank=True)
    # cover_photo = models.ImageField(
    #         upload_to='library_app/images/book_covers',
    #         null=True, blank=True, verbose_name='Book Cover', default=None)

    # genre field is going to be a ManyToManyField because a book may
    # cover many genres, and likewise a genre may be covered by many books
    genre = models.ManyToManyField(Genre,
                                   help_text='Select a genre for this book')


    def __str__(self):
        """String representation of the Model object"""
        return self.title

    def display_genre(self):
        """Create a string for the genre. This is required to display
        genre in Admin"""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    #Define a cleaner description for /admin
    display_genre.short_description = 'Genre'

    def get_absolute_url(self):
        """Returns the url to access a detailed record for the book"""
        return reverse('library_app:book-detail', args=[str(self.id)])


class BookInstance(models.Model):
    """Model representing a specific copy of a book"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
        help_text='Unique ID for this particular book across the library')
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200, help_text='Publisher name')
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True,
                               default='m', help_text='Book availability')

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """String representation of the Model object"""
        return f'{self.id} ({self.book.title})'


class Author(models.Model):
    """A model representation for an Author"""
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=75)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(verbose_name='Died', null=True, blank=True)
    bio = models.TextField(max_length=750, verbose_name='Author Biography',
                            default=None, null=True,
                            blank=True)


    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """url access to the detailed author page"""
        return reverse('library_app:author-detail', args=[str(self.id)])

library_app/forms.py
from django import forms


class ContactForm(forms.Form):
    """Contact form for the user. This could be a feedback,
    a request, or an inquiery """
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True, max_length=100)
    message = forms.CharField(widget=forms.Textarea, required=True)

    def send_mail(self):
        # send email using the self.cleaned_data
        pass

        

library_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from . import models
from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView



class HomeView(generic.TemplateView):

    template_name = 'library_app/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['num_books'] = models.Book.objects.all().count()
        context['num_instances'] = models.BookInstance.objects.all().count()
        context['num_authors'] = models.Author.objects.all().count()
        context['historical_books'] = models.Book.objects.filter(
                                    genre__name__icontains='historical')[:5]
        return context


class BookListView(generic.ListView):
    model = models.Book
    paginate_by = 10



class AuthorListView(generic.ListView):
    model = models.Author
    paginate_by = 10

    def get_queryset(self):
        """List authors by their lastname order"""
        return models.Author.objects.order_by('last_name')


class BookDetailView(generic.DetailView):
    model = models.Book


class AuthorDetailView(generic.DetailView):
    model = models.Author
    
    # def get_context_data(self, **kwargs):
    #     """Display books from the same author"""
    #     context = super().get_context_data(**kwargs)
    #     from .models import Book
    #     context['author_books'] = Book.objects.filter(author_id=self.id)
    #     return context



class AddBookView(LoginRequiredMixin, generic.CreateView):

    model = models.Book
    fields = ('title', 'author', 'summary', 'isbn', 'genre')



class AddAuthorView(LoginRequiredMixin, generic.CreateView):
    model = models.Author
    fields = ('first_name', 'last_name', 'date_of_birth', 'date_of_death', 'bio')


class UpdateAuthorView(LoginRequiredMixin, generic.UpdateView):
    model = models.Author
    fields = ('bio',)
    template_name_suffix = '_update_form'


class GenreListView(generic.ListView):
    model = models.Genre


class ContactView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('thanks')

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.send_mail()
        return super().form_valid(form)



# def email_view(request):
#     """view to check the validity of the contact form"""
#     if request.method == 'GET':
#         # create the empty form for the GET request
#         form = ContactForm()
#     else:
#         # POST method
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             subject = form.cleaned_data['subject']
#             from_email = form.cleaned_data['from_email']
#             message = form.cleaned_data['message']
#             try:
#                 send_mail(subject, message, from_email, ['contact@libraryproject.com'])
#             except BadHeaderError:
#                 return HttpResponse('Invalid header found')
#             return redirect('success')
#     return render(request, 'contact.html', {'form': form})


def success_view(request):
    """View for sending a successful email"""
    return HttpResponse('Success! Thank you for your message. We will get back to you in 48 hours')

library_app/templates/library_app/author_detail.html
{% extends "base.html" %}

{% block content %}

<div id='updateAuthorForm'>
  <h6 id = 'updateAuthorFormHeader'>{{author.last_name}}, {{author.first_name}}</h6>


  {% if author.date_of_birth and author.date_of_death %}
    <p>Born {{author.date_of_birth}}</p>
    <p>Died {{author.date_of_death}}</p>
  {% elif author.date_of_birth %}
      <p>Born {{author.date_of_birth}}, Alive</p>
  {% else %}
      <p></p>
  {% endif %}

  {% if author.bio %}
  <p>{{author.bio}}</p>
</div>

  {% else %}
  <p><strong>No summary is provided for this author</strong></p>
  {% endif %}

  {% for bk in author_books %}
    {{bk.title}}
  {% endfor %}
    <div class="authorDetailButtons">
      <button id='updateAuthorButton' type="button" class="btn btn-light">
      <a href="{% url 'library_app:edit-author' author.pk %}">Edit Author Information</a>
      </button>

      <button id='goBackAuthorButton' type="button" class="btn btn-light">
      <a href="{% url 'library_app:author-list' %}">See All Authors</a>
      </button>
    </div>



{% endblock %}

library_app/templates/library_app/author_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h6 id='authorRegisterForm'>Register new author</h6>
<form id="addAuthorForm" method="post">
  {% csrf_token %}
  {{form|crispy}}
  <input type="submit" class='btn btn-dark' value="Register">
</form>

{% endblock %}

library_app/templates/library_app/author_list.html
{% extends "base.html" %}

{% block content %}
<h5 id='authorListHeader'>Authors:</h5>

  <div class="authorList">

  <ul>
    {% for author in author_list %}
    <li>
      <p><strong><a href="{% url 'library_app:author-detail' author.id %}">
        {{author.last_name}}, {{author.first_name}} </a>
        </strong> </p>
    {% endfor %}
    </li>
  </ul>
</div>
{% endblock %}

library_app/templates/library_app/author_update_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="authorUpdateForm">


  <h6 id='authorUpdateFormHeader'>Update Author Details</h6>

  <form method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-light">Save Changes</button>

  </form>
</div>
{% endblock %}

library_app/templates/library_app/book_detail.html
{% extends "base.html" %}

{% block content %}
  <h4>{{ book.title }}</h4>


  <p><strong>Author: </strong><a href="{% url 'library_app:author-detail'  book.author.pk %}">{{book.author}}</a></p>
  <p><strong>Summary: </strong>{{book.summary}}</p>
  <p><strong>ISBN: </strong>{{book.isbn}}</p>
  <p><strong>Language: </strong>{{book.language}}</p>
  <p><strong>Genre: </strong>

    {% for genre in book.genre.all %}
      {{genre}}
      {% if not forloop.last %}, {% endif %}
    {% endfor %}</p>

    <hr>
    <div style="margin-left:20px;margin-top:20px">
  <h4>Copies</h4>

  {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}
      <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
    {% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
  {% endfor %}
</div>
{% endblock %}

library_app/templates/library_app/book_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<h6 id='bookRegisterForm'>Register new book</h6>
  <form action="{% url 'library_app:add-book' %}" method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" class="btn btn-dark" value="Add Book">
  </form>
{% endblock %}

</div>

library_app/templates/library_app/book_list.html
{% extends "base.html" %}

{% block content %}

  <h6 id='bookListHeader'>Books in records:</h6>
  <hr>
  {% for book in book_list %}

      <ul>
        <li>
      <p><a href="{% url 'library_app:book-detail' book.pk %}"> {{book.title}}</a> by <strong>{{book.author}}</strong></p>
      {% if book.summary %}
      <p><strong>Provided summary: </strong>{{ book.summary }}</p>
      {% endif %}
      {% if book.isbn %}
        <p>ISBN: {{book.isbn}}</p>
      {% endif %}
        </li>

        <hr>
    </ul>





  {% endfor %}
</table>
{% endblock %}

library_app/templates/library_app/index.html
{% extends "base.html" %}

{% block content %}

<div class="landingPage">

  <h5>Welcome to the Library Project</h5>
  <p>Landing page will be created here.</p>
  <hr>
  <h6 id="purposeHeader">The purpose of this project</h6>
  <p id='newsletterForm'>maybe add newsletter subscription email form here?</p>
  <hr>
  <div class="contentStatus">

    <div id='contentStatus2'>
      <h6>Our library consists of</h6><br>
      <p>Total number of books: {{num_books}}</p>
      <p>Total number of books instances: {{num_instances}}</p>
      <p>Total number of authors: {{num_authors}}</p>
    </div>


  <p>Some books in history category are:</p>

  {% for bk in historical_books %}

  <li>
    {% if forloop.last %}

    {% endif %}
    <a href="{% url 'library_app:book-detail' bk.pk %}">{{bk.title}}</a>
  </li>

  {% endfor %}

</div>
</div>

{% endblock %}