LibraryProject/urls.py
from django.contrib import admin
from django.urls import path, include
from library_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library_app.urls')),
    path('contact/', views.ContactView.as_view(), name='contact-form'),
    path('success/', views.success_view, name='thanks'),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),



]

blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path('', views.PostHomeView.as_view(), name='blog-home'),
    path('<int:pk>', views.PostDetailView.as_view(), name='blog-detail'),
    path('<int:pk>/update', views.PostUpdateView.as_view(), name='blog-update'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from accounts.models import User
from django.contrib.auth import get_user_model

User = get_user_model()

class Category(models.Model):
    """Represent a category for a blog post"""
    ###FIX VERBOSE NAME PLURAL
    name = models.CharField(max_length=50,
                help_text='Choose categories for the blog post', default=None)


    def __str__(self):
        """String representation of the Category Object"""
        return self.name



class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, blank=False, null=False)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, default=None)
    tags = models.ManyToManyField('Tag')


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """url access to the detailed post page"""
        return reverse('blog:blog-detail', args=[str(self.id)])

    class Meta:
        ordering = ['-date_created']



class Tag(models.Model):
    name = models.CharField(max_length=155, default=None)

    def __str__(self):
        return self.name


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    # Consider default date add as False until comment approved (with method)
    date_commented = models.DateTimeField(auto_now_add=True)

    # def approve_comment(self):
    #     date_commented = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_commented',]
        unique_together = ['user',]

    def __str__(self):
        return f'{self.post} by {self.user}'

blog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin


class PostHomeView(generic.ListView):
    model = Post
    context_object_name = 'blog_posts'
    paginate_by = 5
    """def get_queryset(self):"""


class PostDetailView(generic.DetailView):
    model = Post


class PostUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Post
    fields = ('title', 'content', 'category', 'tags')
    context_object_name = 'blogpost'
    template_name = 'blog/post_update_form.html'

blog/templates/blog/blog.html
{% extends "base.html" %}

{% block content %}
  <h6 style="text-align: center;">Blog Page</h6><hr>
  <p>Welcome to the blog page.</p>

  {% for post in blogposts %}
    <p>{{post}}</p>
    {# ADD COMMENTS, DATE, ETC #}
  {% endfor %}

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block content %}
  <hr>

  <strong>{{post.title}}</strong>,<hr> <em>Post created: {{post.date_created}}</em><hr>
  {{post.content}}<hr>

  <button type="button" class='btn btn-warning'>
    <a href="{% url 'blog:blog-update' post.pk %}">Edit Post</a>
  </button>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "base.html" %}

{% block content %}
  <h6 style="text-align: center;">Blog Page</h6><hr>

  {% for post in blog_posts %}

  <div class="postContent">

    <ul>
   <p><strong><a href="{% url 'blog:blog-detail' post.pk %}">{{post.title}}</a></strong>,
    created: {{post.date_created}}</p><hr>
    </ul>

  </div>

  {% endfor %}

{% endblock %}

blog/templates/blog/post_update_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="postUpdateForm">
    <h6 id='postUpdateFormHeader'>Update Posts</h6>

    <form method="POST">
      {% csrf_token %}
      {{form|crispy}}
      <button type="submit" class='btn btn-light'>Save Changes</button>
      <button type="button" class='btn btn-dark'><a href="{% url 'blog:blog-home' %}">Dismiss</a></button>
    </form>
  </div>
{% endblock %}