LibraryProject/urls.py
from django.contrib import admin
from django.urls import path, include
from library_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library_app.urls')),
    path('contact/', views.ContactView.as_view(), name='contact-form'),
    path('success/', views.success_view, name='thanks'),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),



]

accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
                                template_name='accounts/login.html'),
                                name='login'),

    path('logout', auth_views.LogoutView.as_view(), name='logout'),

    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('profile/', views.profile, name='profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path('', views.PostHomeView.as_view(), name='blog-home'),
    path('<int:pk>', views.PostDetailView.as_view(), name='blog-detail'),
    path('<int:pk>/update', views.PostUpdateView.as_view(), name='blog-update'),
]

library_app/urls.py
from django.urls import path
from . import views

app_name = 'library_app'

urlpatterns = [
    path('', views.HomeView.as_view(),              name='index'),

    path('catalog/', views.BookListView.as_view(),  name='book-list'),

    path('catalog/<int:pk>', views.BookDetailView.as_view(),
                                                    name='book-detail'),

    path('authors/', views.AuthorListView.as_view(), name='author-list'),

    path('authors/<int:pk>', views.AuthorDetailView.as_view(),
                                                    name='author-detail'),
    path('catalog/addbook', views.AddBookView.as_view(),
                                                    name='add-book'),
    path('authors/addauthor', views.AddAuthorView.as_view(),
                                                    name='add-author'),
    path('authors/<int:pk>/editauthor', views.UpdateAuthorView.as_view(),
                                                    name='edit-author'),
    # path()



]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- BOOTSTRAP4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- JAVASCRIPT -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {# FONTS #}

    {# MASTER CSS #}
    <link rel="stylesheet" href="{% static 'library_app/css/master.css' %}">

  </head>
  <body>
    {# NAVIGATION BAR #}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="nav-link" href="{% url 'library_app:index' %}">
        <img src="/static/library_app/brand_logo/logo.png" height="30">
      </a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'library_app:index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'library_app:book-list' %}">Catalog</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'library_app:author-list' %}">Authors</a>
          </li>

          {% if user.is_authenticated %}

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'library_app:add-book' %}">Add a New Book</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'library_app:add-author' %}">Register New Author</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:blog-home' %}">Library Blog</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'contact-form' %} ">Contact</a>
          </li>


          {% endif %}



          <!-- ACCOUNTS BAR LOGIN LOGOUT SIGNUP PROFILE -->
          {% if user.is_authenticated %}

            <li class="nav-item" id='navbarProfile'>
              <a class="nav-link" href="{% url 'accounts:profile' %}">{{user.username}}'s Profile</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
            </li>
            {% else %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>

          {% endif %}
        </ul>

      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name='searchInput'>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>

  </div>

</nav>



  <div class="container">

    {% block content %}
      {# ALL THE CONTENT GOES HERE #}
    {% endblock %}

    {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %} 
  </div>

  </body>
  <script type="text/javascript" src="{% static 'library_app/js/master.js' %}">
  </script>

</html>

templates/contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h5 id='contactUsForm'>Contact us</h5>
<form method="POST">
  {% csrf_token %}
  {{ form|crispy}}
  <div>
    <input type="submit" value="Send" class="btn btn-primary">
  </div>
</form>
{% endblock %}

templates/email.html
{% extends "base.html" %}

<h5>Contact us</h5>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <div>
    <button type="submit">Send</button>
  </div>
</form>